"""
Summariser — generates a plain-English summary of a codebase using Claude.

Retrieves the most representative chunks (README, entry points, key files)
and asks Claude to write a clear explanation any developer can understand.
"""
from __future__ import annotations
import anthropic
from ingestion.vector_store import search_chunks, get_repo_stats
from config.settings import get_settings


SUMMARY_SYSTEM = """You are a senior developer writing a plain-English explanation of a codebase for other developers.

Your explanation must include:
1. **What this project does** — one clear sentence
2. **The problem it solves** — why does it exist?
3. **How it works** — key components, data flow, main logic (3-5 bullet points)
4. **Key files and what they do** — the most important ones only
5. **Tech stack** — languages, frameworks, tools detected
6. **How to get started** — if you can infer it from the code

Write in plain language. No jargon unless necessary. Assume the reader is a developer 
who is new to this specific project. Be specific — mention actual function names, 
file paths, and patterns you see in the code. Do not make things up.

Format your response in clean Markdown."""


async def generate_summary(repo: str) -> str:
    """
    Generate a full repo summary. Returns Markdown string.
    Pulls representative chunks covering different parts of the codebase.
    """
    s = get_settings()
    stats = get_repo_stats(repo)

    if stats["chunks"] == 0:
        return f"No code has been indexed for `{repo}` yet. Trigger ingestion first."

    # Retrieve chunks covering different aspects of the codebase
    queries = [
        "main entry point how to run start",
        "core business logic primary functionality",
        "data models database schema structure",
        "configuration setup environment",
        "API routes endpoints handlers",
    ]

    seen_paths: set[str] = set()
    all_chunks: list[dict] = []

    for query in queries:
        results = search_chunks(repo=repo, query=query, k=3)
        for r in results:
            if r["path"] not in seen_paths:
                seen_paths.add(r["path"])
                all_chunks.append(r)
        if len(all_chunks) >= 15:
            break

    # Build context block
    context_parts = [f"Repository: {repo}\n"]
    context_parts.append(f"Stats: {stats['files']} files, {stats['chunks']} chunks indexed")
    context_parts.append(f"Languages: {', '.join(stats['languages'])}\n")
    context_parts.append("--- CODE SAMPLES ---\n")

    for chunk in all_chunks[:12]:
        context_parts.append(f"\n### {chunk['path']}\n```{chunk['language']}\n{chunk['text'][:800]}\n```")

    context = "\n".join(context_parts)

    client = anthropic.AsyncAnthropic(api_key=s.anthropic_api_key)
    message = await client.messages.create(
        model=s.claude_model,
        max_tokens=2000,
        system=SUMMARY_SYSTEM,
        messages=[{"role": "user", "content": context}],
    )

    return message.content[0].text


async def generate_pr_comment(repo: str, pr_title: str, changed_files: list[str]) -> str:
    """
    Generate a focused comment for a specific PR — what changed and why it matters.
    """
    s = get_settings()

    # Search for chunks from the changed files
    chunks = []
    for file_path in changed_files[:5]:
        results = search_chunks(repo=repo, query=f"file:{file_path}", k=2)
        chunks.extend(results)

    if not chunks:
        # Fall back to general summary context
        chunks = search_chunks(repo=repo, query=pr_title, k=5)

    context = f"PR Title: {pr_title}\nChanged files: {', '.join(changed_files[:10])}\n\n"
    for chunk in chunks[:6]:
        context += f"\n### {chunk['path']}\n```{chunk['language']}\n{chunk['text'][:600]}\n```"

    client = anthropic.AsyncAnthropic(api_key=s.anthropic_api_key)
    message = await client.messages.create(
        model=s.claude_model,
        max_tokens=800,
        system="""You are a helpful code reviewer. Given a PR title and the relevant code context,
write a SHORT (3-5 bullet points) plain-English summary of what this PR likely changes and why it matters.
Start with a one-line TL;DR. Be specific. Format in Markdown.
End with: > 🤖 *Generated by GitHub Code Intelligence*""",
        messages=[{"role": "user", "content": context}],
    )

    return message.content[0].text
